-- prints the full description of the table 'first_table' from the database 'hbtn_0c_0'
SELECT
    'Table' AS 'Table',
    CONCAT('CREATE TABLE `', TABLE_NAME, '` (\n', GROUP_CONCAT(COLUMN_NAME, ' ', COLUMN_TYPE, ' ', IF(IS_NULLABLE = 'YES', 'DEFAULT NULL', 'NOT NULL'), IF(COLUMN_DEFAULT IS NOT NULL, CONCAT(' DEFAULT "', COLUMN_DEFAULT, '"'), ''), IF(CHARACTER_MAXIMUM_LENGTH IS NOT NULL, CONCAT(' (', CHARACTER_MAXIMUM_LENGTH, ')'), ''), '\n') SEPARATOR ',\n'), '\n) ENGINE=', ENGINE, ' DEFAULT CHARSET=', CHARACTER_SET_NAME, ';') AS 'Create Table'
FROM
    INFORMATION_SCHEMA.TABLES
JOIN
    INFORMATION_SCHEMA.COLUMNS
ON
    INFORMATION_SCHEMA.TABLES.TABLE_NAME = INFORMATION_SCHEMA.COLUMNS.TABLE_NAME
WHERE
    INFORMATION_SCHEMA.TABLES.TABLE_SCHEMA = 'hbtn_0c_0'
    AND INFORMATION_SCHEMA.TABLES.TABLE_NAME = 'first_table';
